### ISSUE TITLE
An anonymous subclass of a sealed trait causes StackOverflowError

### ISSUE THREAD

**Issue by matil019** [scalacenter/tasty-mima#36]
Nice to meet you!

`tastyMiMaReportIssues` crashes with a `StackOverflowError` if source code contains an anonymous class which extends a sealed trait.

### Minimal example

The version of sbt is 1.8.2.

```scala
// src/main/scala/test/Foo.scala
package test

sealed trait Foo

def use1: Foo = new Foo {}
```

```scala
// build.sbt
scalaVersion := "3.2.2"
tastyMiMaPreviousArtifacts := Set(organization.value %% moduleName.value % "0.1.0")
```

```scala
// project/plugins.sbt
addSbtPlugin("ch.epfl.scala" % "sbt-tasty-mima" % "0.2.1")
```

Publish it locally as `0.1.0`, then check the compatibility without any changes to the source code:

```sh
$ find ~/.ivy2/local/default/ -delete # optional
$ sbt 'set version := "0.1.0"' publishLocal && sbt 'set version := "0.1.1"' tastyMiMaReportIssues
```

The last task `tastyMiMaReportIssues` crashes with the following error:

```
[error] java.lang.StackOverflowError
[error]         at tastyquery.Symbols$Symbol.is(Symbols.scala:137)
[error]         at tastymima.Analyzer.compute$1(Analyzer.scala:416)
[error]         at tastymima.Analyzer.classOpenBoundary$$anonfun$1(Analyzer.scala:424)
[error]         at scala.collection.mutable.AnyRefMap.getOrElseUpdate(AnyRefMap.scala:169)
[error]         at tastymima.Analyzer.classOpenBoundary(Analyzer.scala:424)
[error]         at tastymima.Analyzer.compute$1$$anonfun$1(Analyzer.scala:419)
[error]         at scala.collection.StrictOptimizedIterableOps.flatMap(StrictOptimizedIterableOps.scala:118)
[error]         at scala.collection.StrictOptimizedIterableOps.flatMap$(StrictOptimizedIterableOps.scala:105)
[error]         at scala.collection.immutable.Set$Set1.flatMap(Set.scala:156)
[error]         at tastymima.Analyzer.compute$1(Analyzer.scala:421)
[error]         at tastymima.Analyzer.classOpenBoundary$$anonfun$1(Analyzer.scala:424)
[error]         at scala.collection.mutable.AnyRefMap.getOrElseUpdate(AnyRefMap.scala:169)
[error]         at tastymima.Analyzer.classOpenBoundary(Analyzer.scala:424)
[error]         at tastymima.Analyzer.compute$1$$anonfun$1(Analyzer.scala:419)
[error]         at scala.collection.StrictOptimizedIterableOps.flatMap(StrictOptimizedIterableOps.scala:118)
[error]         at scala.collection.StrictOptimizedIterableOps.flatMap$(StrictOptimizedIterableOps.scala:105)
[error]         at scala.collection.immutable.Set$Set1.flatMap(Set.scala:156)
[error]         at tastymima.Analyzer.compute$1(Analyzer.scala:421)
... (repeated stack trace)...
[error]         at tastymima.Analyzer.compute$1(Analyzer.scala:421)
[error]         at tastymima.Analyzer.classOpenBoundary$$anonfun$1(Analyzer.scala:424)
[error]         at scala.collection.mutable.AnyRefMap.getOrElseUpdate(AnyRefMap.scala:169)
[error]         at tastymima.Analyzer.classOpenBoundary(Analyzer.scala:424)
[error]         at tastymima.Analyzer.compute$1$$anonfun$1(Analyzer.scala:419)
[error]         at scala.collection.StrictOptimizedIterableOps.flatMap(StrictOptimizedIterableOps.scala:118)
[error]         at scala.collection.StrictOptimizedIterableOps.flatMap$(StrictOptimizedIterableOps.scala:105)
[error] (tastyMiMaReportIssues) java.lang.StackOverflowError
```

#### Expected result

The check should pass without any compatibility errors.

**Comment by sjrd** [comment]
Thanks for the report! I will look into it.
